# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-11 22:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hunter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=10)),
                ('last_name', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'ordering': ('last_name', 'first_name'),
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_item_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('address', models.CharField(max_length=50)),
                ('year', models.PositiveSmallIntegerField(help_text='(to verify location is being used on the correct log sheet)', validators=[django.core.validators.MinValueValidator(2017)])),
            ],
            options={
                'ordering': ('year', 'line_item_number'),
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incorrect_in_ipd_log', models.BooleanField(default=False)),
                ('missing_from_ipd_log', models.BooleanField(default=False)),
                ('deer_count', models.PositiveSmallIntegerField(default=0)),
                ('deer_gender', models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male')], help_text='(only if deer shot or killed)', max_length=1, null=True)),
                ('deer_points', models.PositiveSmallIntegerField(blank=True, default=None, help_text='(only if deer is male)', null=True)),
                ('deer_tracking', models.NullBooleanField(default=None, help_text='(set only if deer shot or killed)')),
                ('hunter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bow_hunt.Hunter')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bow_hunt.Location')),
            ],
            options={
                'ordering': ('log_sheet__date', 'hunter__last_name', 'hunter__first_name'),
            },
        ),
        migrations.CreateModel(
            name='LogSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('weather', models.CharField(max_length=50)),
                ('temp', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=10)),
                ('last_name', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ('last_name', 'first_name'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='officer',
            unique_together=set([('first_name', 'last_name')]),
        ),
        migrations.AddField(
            model_name='logsheet',
            name='officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bow_hunt.Officer'),
        ),
        migrations.AddField(
            model_name='log',
            name='log_sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bow_hunt.LogSheet'),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set([('line_item_number', 'year')]),
        ),
        migrations.AlterUniqueTogether(
            name='hunter',
            unique_together=set([('first_name', 'last_name')]),
        ),
    ]
