# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-06-27 14:50
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjacentSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acres', models.FloatField()),
                ('is_durand_eastman_golf_course', models.BooleanField(default=False)),
                ('is_durand_eastman_park', models.BooleanField(default=False)),
                ('is_hh_commons', models.BooleanField(default=False)),
                ('is_irondequoit_bay_park_west', models.BooleanField(default=False)),
                ('is_irondequoit_town_land', models.BooleanField(default=False)),
                ('is_vacant', models.BooleanField(default=True)),
                ('adjacent_sites', models.ManyToManyField(blank=True, to='bow_hunt.AdjacentSite')),
            ],
        ),
        migrations.CreateModel(
            name='DataWarning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=70)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Incorrect'), (1, 'Missing')])),
            ],
            options={
                'ordering': ('type', 'label'),
            },
        ),
        migrations.CreateModel(
            name='Deer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField(default=0)),
                ('gender', models.CharField(blank=True, choices=[('F', 'Female (Doe)'), ('M', 'Male (Buck)')], max_length=1, null=True)),
                ('points', models.PositiveSmallIntegerField(blank=True, default=None, help_text='(set only if deer is male, set to 0 if unknown)', null=True)),
                ('tracking', models.NullBooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Deer',
                'ordering': ('log',),
            },
        ),
        migrations.CreateModel(
            name='HHCommonsHunting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_shot', models.TimeField(blank=True, default=None, null=True)),
                ('time_retrieved', models.TimeField(blank=True, default=None, null=True)),
                ('location_notes', models.TextField(blank=True, max_length=50)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'HH Commons hunting',
                'ordering': ('date', 'time_shot', 'hunter'),
            },
        ),
        migrations.CreateModel(
            name='Hunter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=10)),
                ('last_name', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'ordering': ('last_name', 'first_name'),
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_item_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('label', models.CharField(max_length=50)),
                ('year', models.PositiveSmallIntegerField(help_text='(to verify location is being used on the correct log sheet)', validators=[django.core.validators.MinValueValidator(2017)])),
                ('override_line_item_number', models.BooleanField(default=False)),
                ('override_line_item_number_value', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'ordering': ('year', 'line_item_number'),
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=200)),
                ('hunter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bow_hunt.Hunter')),
                ('incorrect_warnings', models.ManyToManyField(blank=True, related_name='incorrect_warnings', to='bow_hunt.DataWarning')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bow_hunt.Location')),
            ],
            options={
                'ordering': ('log_sheet__date', 'location__line_item_number', 'hunter__last_name', 'hunter__first_name'),
            },
        ),
        migrations.CreateModel(
            name='LogSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('comment', models.CharField(blank=True, max_length=200)),
                ('weather', models.CharField(max_length=50)),
                ('temp', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ('date',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LogSheetNonIPD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('comment', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Log sheets (non IPD)',
            },
        ),
        migrations.CreateModel(
            name='NonHunter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bow_hunt.Log')),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=10)),
                ('last_name', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ('last_name', 'first_name'),
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(blank=True, null=True)),
                ('secondary_number', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('street', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('acres', models.FloatField(blank=True, default=None, null=True)),
                ('town_owned', models.BooleanField(default=False)),
                ('comment', models.CharField(blank=True, max_length=200)),
                ('adjacent_sites', models.ManyToManyField(blank=True, to='bow_hunt.AdjacentSite')),
            ],
            options={
                'ordering': ('number', 'street'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='officer',
            unique_together=set([('first_name', 'last_name')]),
        ),
        migrations.AddField(
            model_name='logsheet',
            name='officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bow_hunt.Officer'),
        ),
        migrations.AddField(
            model_name='log',
            name='log_sheet',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bow_hunt.LogSheet'),
        ),
        migrations.AddField(
            model_name='log',
            name='log_sheet_non_ipd',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bow_hunt.LogSheetNonIPD'),
        ),
        migrations.AddField(
            model_name='log',
            name='missing_warnings',
            field=models.ManyToManyField(blank=True, related_name='missing_warnings', to='bow_hunt.DataWarning'),
        ),
        migrations.AddField(
            model_name='location',
            name='site',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bow_hunt.Site'),
        ),
        migrations.AlterUniqueTogether(
            name='hunter',
            unique_together=set([('first_name', 'last_name')]),
        ),
        migrations.AddField(
            model_name='hhcommonshunting',
            name='approved_property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bow_hunt.Location'),
        ),
        migrations.AddField(
            model_name='hhcommonshunting',
            name='hh_rep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.Person', verbose_name='HH rep'),
        ),
        migrations.AddField(
            model_name='hhcommonshunting',
            name='hunter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bow_hunt.Hunter'),
        ),
        migrations.AddField(
            model_name='deer',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bow_hunt.Log'),
        ),
        migrations.AlterUniqueTogether(
            name='site',
            unique_together=set([('number', 'street', 'zip_code')]),
        ),
        migrations.AlterUniqueTogether(
            name='log',
            unique_together=set([('log_sheet', 'location', 'hunter')]),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set([('label', 'line_item_number', 'year')]),
        ),
    ]
