# Generated by Django 2.2.28 on 2026-06-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bow_hunt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='incorrect_warnings',
            field=models.ManyToManyField(blank=True, limit_choices_to={'type': 0}, related_name='incorrect_warnings', to='bow_hunt.DataWarning'),
        ),
        migrations.AlterField(
            model_name='log',
            name='missing_warnings',
            field=models.ManyToManyField(blank=True, limit_choices_to={'type': 1}, related_name='missing_warnings', to='bow_hunt.DataWarning'),
        ),
    ]
