# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-12 13:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bow_hunt', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ('log_sheet__date', 'location__line_item_number', 'hunter__last_name', 'hunter__first_name')},
        ),
    ]
