# Generated by Django 3.2.25 on 2026-06-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bow_hunt', '0002_auto_20260627_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deer',
            name='tracking',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
