# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-12 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bow_hunt', '0003_log_comment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='log',
            unique_together=set([('log_sheet', 'location', 'hunter')]),
        ),
    ]
