# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-13 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bow_hunt', '0004_auto_20220412_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataWarning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Incorrect'), (1, 'Missing')])),
            ],
            options={
                'ordering': ('type', 'label'),
            },
        ),
        migrations.AddField(
            model_name='log',
            name='incorrect_warnings',
            field=models.ManyToManyField(blank=True, related_name='incorrect_warnings', to='bow_hunt.DataWarning'),
        ),
        migrations.AddField(
            model_name='log',
            name='missing_warnings',
            field=models.ManyToManyField(blank=True, related_name='missing_warnings', to='bow_hunt.DataWarning'),
        ),
    ]
