# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-13 12:58
from __future__ import unicode_literals

from django.db import migrations

from bow_hunt.models import DataWarning


# noinspection PyUnusedLocal
def backwards_func(apps, schema_editor):
    apps.get_model('bow_hunt', 'DataWarning').objects.all().delete()


# noinspection PyUnusedLocal
def forwards_func(apps, schema_editor):
    data_warning_model = apps.get_model('bow_hunt', 'DataWarning')

    data_warning_model.objects.create(
        description=(
            'Several hunters were listed as being at this location on the same day, but none were specified '
            'as to who shot the deer.'
        ),
        label='No indication of which hunter shot',
        type=DataWarning.MISSING_WARNING
    )

    data_warning_model.objects.create(
        description=(
            'No value was given if the deer needed to be tracked (off property). Since more resources are needed '
            'when tracking, no value is taken to mean no tracking was needed.')
        ,
        label='Tracking status is missing',
        type=DataWarning.MISSING_WARNING
    )

    data_warning_model.objects.create(
        label='Hunter was missing from the IPD log',
        type=DataWarning.MISSING_WARNING
    )


class Migration(migrations.Migration):

    dependencies = [
        ('bow_hunt', '0005_auto_20220413_0946'),
    ]

    operations = [
        migrations.RunPython(forwards_func, backwards_func)
    ]
