# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-14 12:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bow_hunt', '0007_auto_20220414_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='override_line_item_number',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='override_line_item_number_value',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set([('address', 'line_item_number', 'year')]),
        ),
    ]
