# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-04 15:54
from __future__ import unicode_literals

from django.db import migrations

from bow_hunt.models import DataWarning


# noinspection PyUnusedLocal
def backwards_func(apps, schema_editor):
    apps.get_model('bow_hunt', 'DataWarning').objects.filter(label='Listed hunter didn\'t actually hunt here').delete()


# noinspection PyUnusedLocal
def forwards_func(apps, schema_editor):
    data_warning_model = apps.get_model('bow_hunt', 'DataWarning')

    data_warning_model.objects.create(
        description=(
            'The listed individual was not actually hunting at the location mentioned in the IPD log. Therefore, this '
            'hunter will not be counted in the total for the day.'
        ),
        label='Listed hunter didn\'t actually hunt here',
        type=DataWarning.INCORRECT_WARNING
    )


class Migration(migrations.Migration):

    dependencies = [
        ('bow_hunt', '0009_hunter_first_name_missing_warning'),
    ]

    operations = [
        migrations.RunPython(forwards_func, backwards_func)
    ]
