# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-11 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bow_hunt', '0011_bow_hunt_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField(default=0)),
                ('gender', models.CharField(blank=True, choices=[('F', 'Female (Doe)'), ('M', 'Male (Buck)')], help_text='(only if deer shot)', max_length=1, null=True)),
                ('points', models.PositiveSmallIntegerField(blank=True, default=None, help_text='(only if deer is male)', null=True)),
                ('tracking', models.NullBooleanField(default=None, help_text='(set only if deer shot)')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bow_hunt.Log')),
            ],
            options={
                'verbose_name_plural': 'Deer',
                'ordering': ('log',),
            },
        ),
    ]
