# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-16 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bow_hunt', '0014_auto_20220511_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deer',
            name='points',
            field=models.PositiveSmallIntegerField(blank=True, default=None, help_text='(set only if deer is male)', null=True),
        ),
    ]
