# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-24 10:50
from __future__ import unicode_literals

from django.db import migrations

from bow_hunt.models import DataWarning


# noinspection PyUnusedLocal
def backwards_func(apps, schema_editor):
    apps.get_model('bow_hunt', 'DataWarning').objects.get(label='Points missing').delete()


# noinspection PyUnusedLocal
def forwards_func(apps, schema_editor):
    data_warning_model = apps.get_model('bow_hunt', 'DataWarning')

    data_warning_model.objects.create(
        description=(
            'If a buck is shot, the number of points is usually marked down as part of the deer information.'
        ),
        label='Points missing',
        type=DataWarning.MISSING_WARNING
    )


class Migration(migrations.Migration):

    dependencies = [
        ('bow_hunt', '0015_auto_20220516_0718'),
    ]

    operations = [
        migrations.RunPython(forwards_func, backwards_func)
    ]
