# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-24 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bow_hunt', '0016_points_missing_warning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deer',
            name='points',
            field=models.PositiveSmallIntegerField(blank=True, default=None, help_text='(set only if deer is male, set to 0 if unknown)', null=True),
        ),
    ]
