# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-24 19:49
from __future__ import unicode_literals

from django.db import migrations


# noinspection PyUnusedLocal
def backwards_func(apps, schema_editor):
    missing_name = apps.get_model('bow_hunt', 'DataWarning').objects.get(label='Partial name given')
    missing_name.label = 'Hunter first name missing'
    missing_name.description = (
        'Only a last name for a hunter was given and there are several hunters in the program with the same last name. '
        'No way to tell which hunter it was.'
    )
    missing_name.save()


# noinspection PyUnusedLocal
def forwards_func(apps, schema_editor):
    missing_name = apps.get_model('bow_hunt', 'DataWarning').objects.get(label='Hunter first name missing')
    missing_name.label = 'Partial name given'
    missing_name.description = (
        'Only a partial name was given for a hunter which is not enough to uniquely identify which hunter it was.'
    )
    missing_name.save()


class Migration(migrations.Migration):

    dependencies = [
        ('bow_hunt', '0017_auto_20220524_0704'),
    ]

    operations = [
        migrations.RunPython(forwards_func, backwards_func)
    ]
