# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-29 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bow_hunt', '0018_update_missing_name_warning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deer',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', 'Female (Doe)'), ('M', 'Male (Buck)')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='deer',
            name='tracking',
            field=models.BooleanField(default=False),
        ),
    ]
