# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-06-04 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bow_hunt', '0019_auto_20220529_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonHunter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bow_hunt.Log')),
            ],
        ),
    ]
