# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-06-09 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bow_hunt', '0020_nonhunter'),
    ]

    operations = [
        migrations.AddField(
            model_name='logsheet',
            name='comment',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
