# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-07-06 01:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bow_hunt', '0022_missing_hunter_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjacentSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acres', models.FloatField()),
                ('is_durand_eastman_golf_course', models.BooleanField(default=False)),
                ('is_durand_eastman_park', models.BooleanField(default=False)),
                ('is_hh_commons', models.BooleanField(default=False)),
                ('is_irondequoit_bay_park_west', models.BooleanField(default=False)),
                ('is_irondequoit_town_land', models.BooleanField(default=False)),
                ('is_vacant', models.BooleanField(default=True)),
                ('adjacent_sites', models.ManyToManyField(blank=True, to='bow_hunt.AdjacentSite')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(blank=True, null=True)),
                ('secondary_number', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('street', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('acres', models.FloatField(blank=True, default=None, null=True)),
                ('town_owned', models.BooleanField(default=False)),
                ('comment', models.CharField(blank=True, max_length=200)),
                ('adjacent_sites', models.ManyToManyField(blank=True, to='bow_hunt.AdjacentSite')),
            ],
            options={
                'ordering': ('street', 'number'),
            },
        ),
        migrations.RenameField(
            model_name='location',
            old_name='address',
            new_name='label',
        ),
        migrations.AddField(
            model_name='location',
            name='site',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bow_hunt.Site'),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set([('label', 'line_item_number', 'year')]),
        ),
        migrations.AlterUniqueTogether(
            name='site',
            unique_together=set([('number', 'street', 'zip_code')]),
        ),
    ]
