# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-07-04 18:18
from __future__ import unicode_literals

from django.db import migrations


# noinspection PyUnusedLocal
def backwards_func(apps, schema_editor):
    apps.get_model('bow_hunt', 'AdjacentSite').objects.all().delete()
    apps.get_model('bow_hunt', 'Site').objects.all().delete()


# noinspection PyUnusedLocal
def forwards_func(apps, schema_editor):
    adj_site_model = apps.get_model('bow_hunt', 'AdjacentSite')
    location_model = apps.get_model('bow_hunt', 'Location')
    site_model = apps.get_model('bow_hunt', 'Site')

    durand_eastman_golf_course30_57 = adj_site_model.objects.create(acres=30.57, is_durand_eastman_golf_course=True)

    durand_eastman_park10_72 = adj_site_model.objects.create(acres=10.72, is_durand_eastman_park=True)
    durand_eastman_park30_57 = adj_site_model.objects.create(acres=30.57, is_durand_eastman_park=True)
    durand_eastman_park310_2 = adj_site_model.objects.create(acres=310.2, is_durand_eastman_park=True)
    durand_eastman_park620_5 = adj_site_model.objects.create(acres=620.5, is_durand_eastman_park=True)

    hh0_5 = adj_site_model.objects.create(acres=0.5, is_hh_commons=True)
    hh1_7 = adj_site_model.objects.create(acres=1.7, is_hh_commons=True)
    hh3 = adj_site_model.objects.create(acres=3, is_hh_commons=True)
    hh3_1 = adj_site_model.objects.create(acres=3.1, is_hh_commons=True)
    hh6 = adj_site_model.objects.create(acres=6, is_hh_commons=True)
    hh13_5 = adj_site_model.objects.create(acres=13.5, is_hh_commons=True)
    hh18_45 = adj_site_model.objects.create(acres=18.45, is_hh_commons=True)

    irondequoit_bay_park_west = adj_site_model.objects.create(acres=112.5, is_irondequoit_bay_park_west=True)
    irondequoit_town_land34_4 = adj_site_model.objects.create(acres=34.4, is_irondequoit_town_land=True)

    vacant0_5 = adj_site_model.objects.create(acres=0.5, is_vacant=True)
    vacant0_58 = adj_site_model.objects.create(acres=0.58, is_vacant=True)
    vacant0_73 = adj_site_model.objects.create(acres=0.73, is_vacant=True)
    vacant0_76 = adj_site_model.objects.create(acres=0.76, is_vacant=True)
    vacant0_89 = adj_site_model.objects.create(acres=0.89, is_vacant=True)
    vacant1_03 = adj_site_model.objects.create(acres=1.03, is_vacant=True)
    vacant1_4 = adj_site_model.objects.create(acres=1.4, is_vacant=True)
    vacant1_7 = adj_site_model.objects.create(acres=1.7, is_vacant=True)
    vacant2_1__10_6 = adj_site_model.objects.create(acres=2.1, is_vacant=True)
    vacant2_58 = adj_site_model.objects.create(acres=2.58, is_vacant=True)
    vacant2_8 = adj_site_model.objects.create(acres=2.8, is_vacant=True)
    vacant3_43 = adj_site_model.objects.create(acres=3.43, is_vacant=True)
    vacant3_7 = adj_site_model.objects.create(acres=3.7, is_vacant=True)
    vacant3_9 = adj_site_model.objects.create(acres=3.9, is_vacant=True)
    vacant4_7 = adj_site_model.objects.create(acres=4.7, is_vacant=True)
    vacant4_81 = adj_site_model.objects.create(acres=4.81, is_vacant=True)
    vacant5_37__2_8 = adj_site_model.objects.create(acres=5.37, is_vacant=True)
    vacant5_49 = adj_site_model.objects.create(acres=5.49, is_vacant=True)
    vacant5_6 = adj_site_model.objects.create(acres=5.6, is_vacant=True)
    vacant9_01 = adj_site_model.objects.create(acres=9.01, is_vacant=True)
    vacant10_6 = adj_site_model.objects.create(acres=10.6, is_vacant=True)
    vacant29_2 = adj_site_model.objects.create(acres=29.2, is_vacant=True)

    vacant2_1__10_6.adjacent_sites.add(vacant10_6)
    vacant5_37__2_8.adjacent_sites.add(vacant2_8)

    for location in location_model.objects.all():
        adj_sites = []
        params = None

        if location.label == '1 Whitetail Rise':
            params = {
                'acres': 1.66,
                'number': 1,
                'street': 'Whitetail Rise',
                'zip_code': '14617'
            }
        elif location.label == '10 Imperial Hghts':
            params = {
                'acres': 1.4,
                'number': 10,
                'street': 'E Imperial Hts',
                'zip_code': '14617'
            }
        elif location.label == '31 Dozier Ln':
            params = {
                'acres': 11.08,
                'number': 31,
                'street': 'Dozier Ln',
                'zip_code': '14622'
            }
        elif location.label == '40 Marina Dr':
            params = {
                'acres': 5.3,
                'number': 40,
                'street': 'Marina Dr',
                'zip_code': '14617'
            }
        elif location.label == '40 Nowadaga':
            adj_sites = [vacant5_49]
            params = {
                'acres': 0.17,
                'number': 40,
                'street': 'Nowadaga Dr',
                'zip_code': '14617'
            }
        elif location.label in ['48 Breezeway', '48 Breezeway Dr.']:
            params = {
                'acres': 0.88,
                'number': 48,
                'street': 'Breezeway Dr',
                'zip_code': '14622'
            }
        elif location.label == '49 Sagamore Dr':
            adj_sites = [vacant0_58]
            params = {
                'acres': 0.47,
                'number': 49,
                'street': 'Sagamore Dr',
                'zip_code': '14617'
            }
        elif location.label == '70 Dogwood Ln':
            adj_sites = [hh1_7]
            params = {
                'acres': 0.77,
                'number': 70,
                'street': 'Dogwood Ln',
                'zip_code': '14622'
            }
        elif location.label in ['85 Valleyview', '85 Valleyview Cr']:
            adj_sites = [vacant0_89, vacant3_7]
            params = {
                'acres': 1.9,
                'number': 85,
                'street': 'Valley View Cres',
                'zip_code': '14617'
            }
        elif location.label == '90 Indian Trail':
            adj_sites = [vacant1_7, vacant2_58]
            params = {
                'acres': 1.6,
                'number': 90,
                'street': 'Indian Trl',
                'zip_code': '14622'
            }
        elif location.label == '92 Muirwoods':
            adj_sites = [vacant29_2]
            params = {
                'acres': 3.95,
                'number': 92,
                'street': 'Muirwoods Ln',
                'zip_code': '14622'
            }
        elif location.label == '97 Nob Hill':
            params = {
                'acres': 0.68,
                'number': 97,
                'street': 'Nob Hl',
                'zip_code': '14617'
            }
        elif location.label == '98/108 Fox Hall':
            adj_sites = [irondequoit_bay_park_west]
            params = {
                'acres': 1.66,
                'comment': 'Two properties are combined and listed as a single site.',
                'number': 98,
                'secondary_number': 108,
                'street': 'Foxhall Dr',
                'zip_code': '14609'
            }
        elif location.label == '105 Conifer Ln':
            adj_sites = [hh1_7]
            params = {
                'acres': 1.4,
                'number': 105,
                'street': 'Conifer Ln',
                'zip_code': '14622'
            }
        elif location.label == '105 Scotch Ln':
            adj_sites = [vacant2_1__10_6]
            params = {
                'acres': 1.9,
                'number': 105,
                'street': 'Scotch Ln',
                'zip_code': '14617'
            }
        elif location.label == '120 Nob Hill':
            params = {
                'comment': 'Address does not exist.',
                'number': 120,
                'street': 'Nob Hl',
                'zip_code': '14617'
            }
        elif location.label == '121 Nob Hill':
            params = {
                'acres': 0.87,
                'number': 121,
                'street': 'Nob Hl',
                'zip_code': '14617'
            }
        elif location.label == '125 Conifer Ln':
            adj_sites = [durand_eastman_park620_5]
            params = {
                'acres': 1.8,
                'number': 125,
                'street': 'Conifer Ln',
                'zip_code': '14622'
            }
        elif location.label == '151 Conifer Ln':
            adj_sites = [durand_eastman_park620_5, hh18_45]
            params = {
                'acres': 1.7,
                'number': 151,
                'street': 'Conifer Ln',
                'zip_code': '14622'
            }
        elif location.label == '159 Wisner Rd':
            adj_sites = [hh1_7]
            params = {
                'acres': 1.4,
                'number': 159,
                'street': 'Wisner Rd',
                'zip_code': '14622'
            }
        elif location.label == '160 Densmore Rd':
            params = {
                'acres': 11.5,
                'number': 160,
                'street': 'Densore Rd',
                'zip_code': '14609'
            }
        elif location.label == '160 Nob Hill':
            adj_sites = [vacant3_43]
            params = {
                'acres': 5.6,
                'number': 160,
                'street': 'Nob Hl',
                'zip_code': '14617'
            }
        elif location.label == '172 Old North Hl':
            params = {
                'acres': 0.78,
                'number': 172,
                'street': 'Old North Hl',
                'zip_code': '14617'
            }
        elif location.label == '180 Sachem Way':
            params = {
                'acres': 8.26,
                'number': 180,
                'street': 'Sachem Way',
                'zip_code': '14617'
            }
        elif location.label == '196 Eastgate':
            adj_sites = [irondequoit_town_land34_4]
            params = {
                'acres': 0.59,
                'number': 196,
                'street': 'Eastgate Dr',
                'zip_code': '14617'
            }
        elif location.label == '201 Nob Hill':
            adj_sites = [durand_eastman_park620_5]
            params = {
                'acres': 1.8,
                'number': 201,
                'street': 'Nob Hl',
                'zip_code': '14617'
            }
        elif location.label == '202 Legionaire':
            adj_sites = [vacant5_49]
            params = {
                'acres': 0.15,
                'number': 202,
                'street': 'Legionaire Dr',
                'zip_code': '14617'
            }
        elif location.label == '210 Nob Hill':
            adj_sites = [durand_eastman_park310_2]
            params = {
                'acres': 1.9,
                'number': 210,
                'street': 'Nob Hl',
                'zip_code': '14617'
            }
        elif location.label == '217 Huntington':
            adj_sites = [hh0_5, hh1_7]
            params = {
                'acres': 1,
                'number': 217,
                'street': 'Huntington Hls N',
                'zip_code': '14622'
            }
        elif location.label == '227 Huntington Hls':
            params = {
                'comment': 'This address does not exist.',
                'number': 227,
                'street': 'Huntington Hls',
                'zip_code': '14622'
            }
        elif location.label == '235 Harvington':
            adj_sites = [vacant5_37__2_8]
            params = {
                'acres': 1,
                'number': 235,
                'street': 'Harvington Dr',
                'zip_code': '14617'
            }
        elif location.label == '237 Mt Airy Dr':
            params = {
                'acres': 0.79,
                'number': 237,
                'street': 'Mt Airy Dr',
                'zip_code': '14617'
            }
        elif location.label == '246 St Joseph':
            adj_sites = [vacant1_03, vacant0_73, vacant9_01]
            params = {
                'acres': 1.98,
                'number': 246,
                'street': 'St Joseph St',
                'zip_code': '14617'
            }
        elif location.label == '258 St. Joseph':
            adj_sites = [vacant9_01]
            params = {
                'acres': 5,
                'number': 258,
                'street': 'St Joseph St',
                'zip_code': '14617'
            }
        elif location.label == '285 Totem Trail':
            params = {
                'acres': 7.15,
                'number': 285,
                'street': 'Totem Trl',
                'zip_code': '14617'
            }
        elif location.label in ['300 Huntington', '300 Huntington Hls']:
            adj_sites = [hh13_5]
            params = {
                'acres': 2.1,
                'number': 300,
                'street': 'Huntington Hls',
                'zip_code': '14622'
            }
        elif location.label == '311 Hoffman Rd':
            adj_sites = [vacant29_2, hh6]
            params = {
                'acres': 0.36,
                'number': 311,
                'street': 'Hoffman Rd',
                'zip_code': '14622'
            }
        elif location.label in ['312 Seneca Pk', '312 Seneca Park Ave']:
            adj_sites = [vacant9_01]
            params = {
                'acres': 0.89,
                'number': 312,
                'street': 'Seneca Park Ave',
                'zip_code': '14617'
            }
        elif location.label in ['325 VanVoorhis', '325 Van Voorhis']:
            adj_sites = [vacant1_4]
            params = {
                'acres': 5.8,
                'number': 325,
                'street': 'Van Voorhis Ave',
                'zip_code': '14617'
            }
        elif location.label == '329 Orchard Pk':
            params = {
                'acres': 2.29,
                'number': 329,
                'street': 'Orchard Park Blvd',
                'zip_code': '14609'
            }
        elif location.label == '336 St. Joseph':
            adj_sites = [vacant4_7, vacant4_81, vacant9_01]
            params = {
                'acres': 7.2,
                'number': 336,
                'street': 'St Joseph St',
                'zip_code': '14617'
            }
        elif location.label == '337 Rock Beach':
            params = {
                'acres': 1.05,
                'number': 337,
                'street': 'Rock Beach Rd',
                'zip_code': '14617'
            }
        elif location.label in ['343 Huntington', '343 Huntington Hls']:
            adj_sites = [hh3, hh3_1]
            params = {
                'acres': 1.8,
                'number': 343,
                'street': 'Huntington Hls',
                'zip_code': '14622'
            }
        elif location.label == '352 St. Joseph':
            params = {
                'acres': 4.09,
                'number': 352,
                'street': 'St Joseph St',
                'zip_code': '14617'
            }
        elif location.label == '367 Bayview':
            params = {
                'acres': 1.1,
                'number': 367,
                'street': 'Bay View Rd',
                'zip_code': '14609'
            }
        elif location.label == '375 Oakridge':
            adj_sites = [vacant5_37__2_8]
            params = {
                'acres': 1.1,
                'number': 375,
                'street': 'Oakridge Dr',
                'zip_code': '14617'
            }
        elif location.label == '385 Seneca Park':
            params = {
                'acres': 16.7,
                'comment': (
                    'According to the IPD 2020 Bow Hunting Properties map, this property matches 379 Seneca Park Ave. '
                    '385 Seneca Park Ave is not listed anywhere.'
                ),
                'number': 385,
                'street': 'Seneca Park Ave',
                'town_owned': True,
                'zip_code': '14617'
            }
        elif location.label == '395 Hoffman Rd':
            adj_sites = [vacant29_2, hh6]
            params = {
                'acres': 2.29,
                'number': 395,
                'street': 'Hoffman Rd',
                'zip_code': '14622'
            }
        elif location.label == '397 Bayview':
            params = {
                'acres': 1.9,
                'number': 397,
                'street': 'Bay View Rd',
                'zip_code': 14609
            }
        elif location.label == '454 St. Joseph':
            params = {
                'acres': 1.48,
                'number': 454,
                'street': 'St Joseph St',
                'zip_code': '14617'
            }
        elif location.label == '460 Vanvoorhis':
            params = {
                'acres': 1.2,
                'number': 460,
                'street': 'Van Voorhis Ave',
                'zip_code': '14617'
            }
        elif location.label == '465 Vanvoorhis':
            params = {
                'acres': 0.46,
                'number': 465,
                'street': 'Van Voorhis Ave',
                'zip_code': '14617'
            }
        elif location.label == '475 Hoffman Rd':
            adj_sites = [hh6]
            params = {
                'acres': 1.7,
                'number': 475,
                'street': 'Hoffman Rd',
                'zip_code': '14622'
            }
        elif location.label == '485 Vanvoorhis':
            params = {
                'acres': 0.48,
                'number': 485,
                'street': 'Van Voorhis Ave',
                'zip_code': '14617'
            }
        elif location.label == '487 Pinegrove Ave':
            adj_sites = [durand_eastman_park310_2]
            params = {
                'acres': 5.37,
                'number': 487,
                'street': 'Pinegrove Ave',
                'zip_code': '14617'
            }
        elif location.label == '491 Hoffman Rd':
            adj_sites = [hh6]
            params = {
                'acres': 0.83,
                'number': 491,
                'street': 'Hoffman Rd',
                'zip_code': '14622'
            }
        elif location.label == '499 Pinegrove Ave':
            adj_sites = [durand_eastman_park30_57]
            params = {
                'acres': 5.14,
                'number': 487,
                'street': 'Pinegrove Ave',
                'zip_code': '14617'
            }
        elif location.label == '505 Vanvoorhis':
            params = {
                'acres': 1,
                'number': 505,
                'street': 'Van Voorhis Ave',
                'zip_code': '14617'
            }
        elif location.label == '506 Vanvoorhis':
            params = {
                'acres': 1,
                'number': 506,
                'street': 'Van Voorhis Ave',
                'zip_code': '14617'
            }
        elif location.label == '510 Thomas Ave':
            params = {
                'acres': 0.89,
                'number': 510,
                'street': 'Thomas Ave',
                'zip_code': '14617'
            }
        elif location.label == '515 Sagamore':
            params = {
                'comment': 'Town owned land? No information or size available.',
                'number': 515,
                'street': 'Sagamore Dr',
                'town_owned': True,
                'zip_code': '14617'
            }
        elif location.label == '525 Vanvoorhis':
            params = {
                'acres': 0.75,
                'number': 525,
                'street': 'Van Voorhis Ave',
                'zip_code': '14617'
            }
        elif location.label == '549 Vanvoorhis':
            params = {
                'acres': 0.7,
                'number': 549,
                'street': 'Van Voorhis Ave',
                'zip_code': '14617'
            }
        elif location.label == '555 Sagamore':
            params = {
                'acres': 1,
                'number': 555,
                'street': 'Sagamore Dr',
                'zip_code': '14617'
            }
        elif location.label == '561 Vanvoorhis':
            params = {
                'acres': 0.9,
                'number': 561,
                'street': 'Van Voorhis Ave',
                'zip_code': '14617'
            }
        elif location.label == '575 Vanvoorhis':
            params = {
                'acres': 0.44,
                'number': 575,
                'street': 'Van Voorhis Ave',
                'zip_code': '14617'
            }
        elif location.label == '581 Pinegrove Ave':
            params = {
                'acres': 0.87,
                'number': 581,
                'street': 'Pinegrove Ave',
                'zip_code': '14617'
            }
        elif location.label == '587 Pinegrove Ave':
            params = {
                'acres': 0.83,
                'number': 587,
                'street': 'Pinegrove Ave',
                'zip_code': '14617'
            }
        elif location.label == '591 Thomas Ave':
            params = {
                'acres': 8.1,
                'number': 591,
                'street': 'Thomas Ave',
                'zip_code': '14617'
            }
        elif location.label == '602 VanVoorhis':
            params = {
                'acres': 1,
                'number': 602,
                'street': 'Van Voorhis Ave',
                'zip_code': '14617'
            }
        elif location.label == '690 Thomas Ave':
            params = {
                'acres': 22.1,
                'number': 690,
                'street': 'Thomas Ave',
                'zip_code': '14617'
            }
        elif location.label == '731 Kings Hwy':
            adj_sites = [durand_eastman_park10_72, durand_eastman_park310_2]
            params = {
                'acres': 1.54,
                'number': 731,
                'street': 'Kings Hwy N',
                'zip_code': '14617'
            }
        elif location.label == '733 Kings Hwy':
            params = {
                'comment': 'Town owned land? No information or size available.',
                'number': 733,
                'street': 'Kings Hwy N',
                'town_owned': True,
                'zip_code': '14617'
            }
        elif location.label == '770 Vanvoorhis':
            params = {
                'acres': 0.38,
                'number': 770,
                'street': 'Van Voorhis Ave',
                'zip_code': '14617'
            }
        elif location.label == '915 Kings Hw':
            params = {
                'comment': 'Town owned land? No information or size available.',
                'number': 915,
                'street': 'Kings Hwy N',
                'town_owned': True,
                'zip_code': '14617'
            }
        elif location.label == '959 Winona Blvd':
            params = {
                'acres': 4.24,
                'number': 959,
                'street': 'Winona Blvd',
                'zip_code': '14617'
            }
        elif location.label == '994 Brown Rd':
            adj_sites = [vacant5_6]
            params = {
                'acres': 5.7,
                'number': 994,
                'street': 'Brown Rd',
                'zip_code': '14622'
            }
        elif location.label == '1015 N Kings Hwy':
            adj_sites = [durand_eastman_golf_course30_57]
            params = {
                'acres': 4.7,
                'number': 1015,
                'street': 'Kings Hwy N',
                'zip_code': '14617'
            }
        elif location.label in ['1301 Lakeshore', '1301 Lake Shore Blvd', 'Camp Eastman']:
            params = {
                'acres': 90.9,
                'comment': 'This is Camp Eastman.',
                'number': 1301,
                'street': 'Lakeshore Blvd',
                'town_owned': True,
                'zip_code': '14617'
            }
        elif location.label == '1791 Titus Ave':
            params = {
                'acres': 5.6,
                'number': 1791,
                'street': 'Titus Ave',
                'zip_code': '14622'
            }
        elif location.label == '1944 Titus Ave':
            adj_sites = [vacant0_5, vacant29_2]
            params = {
                'acres': 3.82,
                'number': 1944,
                'street': 'Titus Ave',
                'zip_code': '14622'
            }
        elif location.label == '2794 Oakview Dr':
            adj_sites = [durand_eastman_park310_2]
            params = {
                'acres': 2.2,
                'number': 2794,
                'street': 'Oakview Dr',
                'zip_code': '14617'
            }
        elif location.label == '2815 Oakview Dr':
            adj_sites = [durand_eastman_park310_2]
            params = {
                'acres': 1.5,
                'number': 2815,
                'street': 'Oakview Dr',
                'zip_code': '14617'
            }
        elif location.label in ['3991 St Paul', '3991 St. Paul Blvd']:
            adj_sites = [vacant0_76]
            params = {
                'acres': 1.3,
                'number': 3991,
                'street': 'St Paul Blvd',
                'zip_code': '14617'
            }
        elif location.label == '4400 St Paul':
            params = {
                'acres': 0.45,
                'number': 4400,
                'street': 'St Paul Blvd',
                'zip_code': '14617'
            }
        elif location.label in ['4421 St Paul', '4421 St Paul Blvd']:
            params = {
                'acres': 3.18,
                'number': 4421,
                'street': 'St Paul Blvd',
                'town_owned': True,
                'zip_code': '14617'
            }
        elif location.label == '5185 St. Paul':
            params = {
                'acres': 0.43,
                'number': 5185,
                'street': 'St Paul Blvd',
                'zip_code': '14617'
            }
        elif location.label == '5250 St Paul Blvd':
            params = {
                'comment': 'This address does not exist.',
                'number': 5250,
                'street': 'St Paul Blvd',
                'zip_code': '14617'
            }
        elif location.label == 'Eastman Estates':
            params = {
                'comment': 'There is no indication as to which site this is.',
                'street': '',
                'zip_code': '14622'
            }
        elif location.label == 'Muirwoods':
            params = {
                'comment': 'Town owned land? No information or size available.',
                'street': 'Sagamore Dr',
                'town_owned': True,
                'zip_code': '14622'
            }
        elif location.label == 'Newport Cove':
            params = {
                'acres': 24.3,
                'comment': (
                    'According to the IPD 2020 Bow Hunting Properties map, this property matches 255 Newport Rd. '
                    'Newport Cove is not listed anywhere.'
                ),
                'street': 'Newport Rd',
                'town_owned': True,
                'zip_code': '14622'
            }
        elif location.label in ['Lakeshore/Rock Beach', 'Rock Beach Rd', 'Rock Beach Rd/Lakeshore Blvd']:
            adj_sites = [vacant1_4]
            params = {
                'acres': 4.8,
                'street': 'Lake Shore Blvd',
                'zip_code': '14617'
            }
        elif location.label in ['TOI Rudman', 'TOI Rudman Rd']:
            params = {
                'acres': 3,
                'street': 'Rudman Dr',
                'town_owned': True,
                'zip_code': '14622'
            }
        elif location.label == 'Scotch Ln':
            params = {
                'acres': 2.1,
                'comment': 'Adjacent to the 10.6 acre Wildmere property owned by the same person.',
                'street': 'Scotch Ln',
                'zip_code': '14617'
            }
        elif location.label == 'SE Plant':
            params = {
                'comment': 'Town owned land? No information or size available.',
                'street': 'SE Plant',
                'town_owned': True,
                'zip_code': ''
            }
        elif location.label in ['Garden Plots (Spring Valley)', 'Spring Valley Dr']:
            params = {
                'acres': 0.22,
                'comment': 'Two properties are combined and listed as a single site.',
                'street': 'Spring Valley Dr',
                'zip_code': '14622'
            }
        elif location.label == 'St Jos/Van Voorh':
            adj_sites = [vacant3_9]
            params = {
                'acres': 8,
                'street': 'St Joseph St',
                'zip_code': '14617'
            }
        elif location.label == 'St. Paul / Winona':
            params = {
                'comment': 'No indicate of which site this was.',
                'street': '',
                'zip_code': '14617'
            }
        elif location.label == 'TOI Birch Hills':
            params = {
                'acres': 20.03,
                'comment': (
                    'According to the IPD 2020 Bow Hunting Properties map, this property matches Birch Hills Park.'
                ),
                'street': 'Birch Hills Park',
                'town_owned': True,
                'zip_code': '14622'
            }
        elif location.label == 'Wildmere':
            params = {
                'acres': 10.6,
                'comment': 'Adjacent to the 2.1 acre Scotch Ln property owned by the same person.',
                'street': 'Wildmere',
                'zip_code': '14617'
            }
        elif location.label == 'Woodcraft':
            params = {
                'comment': 'Town owned land? No information or size available.',
                'street': 'Woodcraft',
                'town_owned': True,
                'zip_code': ''
            }

        if params:
            site, _ = site_model.objects.get_or_create(
                number=params.get('number'), street=params['street'], zip_code=params['zip_code'],
                defaults=params
            )

            for adj_site in adj_sites:
                site.adjacent_sites.add(adj_site)

            location.site = site
            location.save()
        else:
            raise RuntimeError(f'unknown location: "{location.label}"')


class Migration(migrations.Migration):

    dependencies = [
        ('bow_hunt', '0023_auto_20220705_2159'),
    ]

    operations = [
        migrations.RunPython(forwards_func, backwards_func)
    ]
