# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-12-31 18:59
from __future__ import unicode_literals

from django.db import migrations


# noinspection PyUnusedLocal
def backwards_func(apps, schema_editor):
    data_warning_model = apps.get_model('bow_hunt', 'DataWarning')
    no_hunter_listed = data_warning_model.objects.get(
        label='No indication of which hunter shot (assign to <unknown> hunter)'
    )
    no_hunter_listed.label = 'No indication of which hunter shot'
    no_hunter_listed.save()


# noinspection PyUnusedLocal
def forwards_func(apps, schema_editor):
    data_warning_model = apps.get_model('bow_hunt', 'DataWarning')
    no_hunter_listed = data_warning_model.objects.get(label='No indication of which hunter shot')
    no_hunter_listed.label = 'No indication of which hunter shot (assign to <unknown> hunter)'
    no_hunter_listed.save()


class Migration(migrations.Migration):

    dependencies = [
        ('bow_hunt', '0027_auto_20221231_1403'),
    ]

    operations = [
        migrations.RunPython(forwards_func, backwards_func)
    ]
