# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-12-30 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bow_hunt', '0028_no_hunter_for_shot_listed_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogSheetNonIPD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('comment', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ('date',),
                'abstract': False,
            },
        ),
    ]
