# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-12-30 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bow_hunt', '0029_logsheetnonipd'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logsheetnonipd',
            options={'verbose_name_plural': 'Log sheets (non IPD)'},
        ),
        migrations.AddField(
            model_name='log',
            name='log_sheet_non_ipd',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bow_hunt.LogSheetNonIPD'),
        ),
        migrations.AlterField(
            model_name='log',
            name='log_sheet',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bow_hunt.LogSheet'),
        ),
    ]
