# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-01-01 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0005_auto_20210107_1506'),
        ('bow_hunt', '0030_auto_20231230_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='HHCommonsHunting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_shot', models.TimeField(blank=True, default=None, null=True)),
                ('time_retrieved', models.TimeField(blank=True, default=None, null=True)),
                ('location_notes', models.TextField(blank=True, max_length=50)),
                ('comment', models.TextField(blank=True, null=True)),
                ('approved_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bow_hunt.Location')),
                ('hh_rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.Person', verbose_name='HH rep')),
                ('hunter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bow_hunt.Hunter')),
            ],
            options={
                'verbose_name_plural': 'HH Commons hunting',
                'ordering': ('date', 'time_shot', 'hunter'),
            },
        ),
    ]
