# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-01-12 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bow_hunt', '0031_hhcommonshunting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deer',
            name='tracking',
            field=models.NullBooleanField(default=False),
        ),
    ]
