# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-20 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('posted_on', models.DateField(blank=True)),
                ('posted_until', models.DateField(help_text='Last date in which to display this article')),
                ('short_desc', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ('posted_on', 'title'),
            },
        ),
    ]
