# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-23 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-posted_on', 'title')},
        ),
    ]
