# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-31 19:12
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20201023_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='desc',
            field=tinymce.models.HTMLField(),
        ),
    ]
