# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-06-27 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Board members',
            },
        ),
        migrations.CreateModel(
            name='BoardTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elected_date', models.DateField()),
                ('office', models.CharField(choices=[('d1', 'Director at Large 1'), ('d2', 'Director at Large 2'), ('p', 'President'), ('s', 'Secretary'), ('t', 'Treasurer'), ('vp', 'Vice President')], max_length=2)),
            ],
            options={
                'ordering': ('-elected_date', 'person'),
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LotNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'ordering': ('property', 'lot_number'),
            },
        ),
        migrations.CreateModel(
            name='MailingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20)),
                ('line1', models.CharField(max_length=50)),
                ('line2', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('state', localflavor.us.models.USStateField(max_length=2)),
                ('zip_code', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Mailing addresses',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('prefix', models.CharField(blank=True, default=None, max_length=5, null=True)),
                ('suffix', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Example: 000-000-0000.', max_length=128, region='US')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('last_name', 'first_name'),
            },
        ),
        migrations.CreateModel(
            name='PersonEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='residents.Email')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.Person')),
            ],
            options={
                'ordering': ('person', 'email'),
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('house_number', models.SmallIntegerField()),
                ('in_hh', models.BooleanField(default=True)),
                ('outside_mailing_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='residents.MailingAddress')),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ('street', 'house_number'),
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'ordering': ('property_type',),
            },
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'ordering': ('street',),
            },
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.PropertyType'),
        ),
        migrations.AddField(
            model_name='property',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.Street'),
        ),
        migrations.AddField(
            model_name='person',
            name='emails',
            field=models.ManyToManyField(through='residents.PersonEmail', to='residents.Email'),
        ),
        migrations.AddField(
            model_name='person',
            name='residential_property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.Property'),
        ),
        migrations.AddField(
            model_name='lotnumber',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.Property'),
        ),
        migrations.AddField(
            model_name='boardterm',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.Person'),
        ),
        migrations.AddField(
            model_name='board',
            name='director_at_large_1',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='director_at_large_1', to='residents.Person'),
        ),
        migrations.AddField(
            model_name='board',
            name='director_at_large_2',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='director_at_large_2', to='residents.Person'),
        ),
        migrations.AddField(
            model_name='board',
            name='president',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='president', to='residents.Person'),
        ),
        migrations.AddField(
            model_name='board',
            name='secretary',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='secretary', to='residents.Person'),
        ),
        migrations.AddField(
            model_name='board',
            name='treasurer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='treasurer', to='residents.Person'),
        ),
        migrations.AddField(
            model_name='board',
            name='vice_president',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='vice_president', to='residents.Person'),
        ),
        migrations.AlterUniqueTogether(
            name='lotnumber',
            unique_together=set([('lot_number', 'property')]),
        ),
    ]
