# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-26 03:19
from __future__ import unicode_literals

from django.db import migrations


# noinspection PyUnusedLocal
def backwards_func(apps, schema_editor):
    apps.get_model('residents', 'EmailType').objects.all().delete()
    apps.get_model('residents', 'PropertyType').objects.all().delete()
    apps.get_model('residents', 'Street').objects.all().delete()


# noinspection PyUnusedLocal
def forwards_func(apps, schema_editor):
    email_type_model = apps.get_model('residents', 'EmailType')

    email_type_model.objects.create(email_type='Notification')
    email_type_model.objects.create(email_type='Personal')
    email_type_model.objects.create(email_type='Resident')

    property_type_model = apps.get_model('residents', 'PropertyType')

    property_type_model.objects.create(property_type='home')
    property_type_model.objects.create(property_type='lot')

    streets = [
        'Conifer Lane', 'Dogwood Lane', 'Hoffman Road', 'Huntington Hills Center', 'Huntington Hills North',
        'Huntington Hills South', 'Rainbow Drive', 'Spring Valley Drive', 'Wisner Road'
    ]
    street_model = apps.get_model('residents', 'Street')

    for street in streets:
        street_model.objects.create(street=street)


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func, backwards_func)
    ]
