# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-23 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0002_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Board Members',
            },
        ),
        migrations.AddField(
            model_name='person',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Example: 000-000-0000.', max_length=128, region='US'),
        ),
        migrations.AddField(
            model_name='board',
            name='director_at_large_1',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='director_at_large_1', to='residents.Person'),
        ),
        migrations.AddField(
            model_name='board',
            name='director_at_large_2',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='director_at_large_2', to='residents.Person'),
        ),
        migrations.AddField(
            model_name='board',
            name='president',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='president', to='residents.Person'),
        ),
        migrations.AddField(
            model_name='board',
            name='secretary',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='secretary', to='residents.Person'),
        ),
        migrations.AddField(
            model_name='board',
            name='treasurer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='treasurer', to='residents.Person'),
        ),
        migrations.AddField(
            model_name='board',
            name='vice_president',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='vice_president', to='residents.Person'),
        ),
    ]
