# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-07 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0004_person_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elected_date', models.DateField()),
                ('office', models.CharField(choices=[('d1', 'Director at Large 1'), ('d2', 'Director at Large 2'), ('p', 'President'), ('s', 'Secretary'), ('t', 'Treasurer'), ('vp', 'Vice President')], max_length=2)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.Person')),
            ],
            options={
                'ordering': ('-elected_date', 'person'),
            },
        ),
        migrations.AlterModelOptions(
            name='board',
            options={'verbose_name_plural': 'Board members'},
        ),
    ]
