# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-03-08 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0005_auto_20210107_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='new_emails',
            field=models.ManyToManyField(to='residents.NewEmail'),
        ),
    ]
