# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-03-08 18:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_lists', '0002_remove_mailinglist_email_type'),
        ('residents', '0007_move_email'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='email',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='email',
            name='email_type',
        ),
        migrations.RemoveField(
            model_name='email',
            name='person',
        ),
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.DeleteModel(
            name='EmailType',
        ),
    ]
