# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-03-08 19:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0008_auto_20250308_1348'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewEmail',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='new_emails',
            new_name='emails',
        ),
    ]
