# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-03-08 21:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0009_auto_20250308_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='residents.Email')),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='emails',
            field=models.ManyToManyField(related_name='old_email', to='residents.Email'),
        ),
        migrations.AddField(
            model_name='personemail',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.Person'),
        ),
        migrations.AddField(
            model_name='person',
            name='new_emails',
            field=models.ManyToManyField(through='residents.PersonEmail', to='residents.Email'),
        ),
    ]
