# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-03-08 21:45
from __future__ import unicode_literals

from django.db import migrations


# noinspection PyUnusedLocal
def backwards_func(apps, schema_editor):
    apps.get_model('residents', 'NewEmail').objects.all().delete()


# noinspection PyUnusedLocal
def forwards_func(apps, schema_editor):
    person_model = apps.get_model('residents', 'Person')
    person_email_model = apps.get_model('residents', 'PersonEmail')

    for person in person_model.objects.all():
        for email in person.emails.all():
            person_email_model.objects.create(
                email=email,
                person=person
            )


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0010_auto_20250308_1635'),
    ]

    operations = [
        migrations.RunPython(forwards_func, backwards_func)
    ]
