# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-03-08 21:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0011_move_emails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personemail',
            options={'ordering': ('person', 'email')},
        ),
        migrations.RemoveField(
            model_name='person',
            name='emails',
        ),
    ]
