# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-01 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import gallery.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.PositiveIntegerField(editable=False)),
                ('image', models.ImageField(height_field='height', upload_to=gallery.models.gallery_path, width_field='width')),
                ('long_description', models.TextField(blank=True)),
                ('page', models.PositiveSmallIntegerField()),
                ('short_description', models.CharField(blank=True, max_length=80)),
                ('tnail', models.ImageField(editable=False, height_field='tnail_height', upload_to=gallery.models.gallery_tnail_path, width_field='tnail_width')),
                ('tnail_height', models.PositiveIntegerField(editable=False)),
                ('tnail_width', models.PositiveIntegerField(editable=False)),
                ('width', models.PositiveIntegerField(editable=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.Owner')),
            ],
        ),
    ]
