# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-02 17:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='owner',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ('owner', 'page')},
        ),
    ]
