# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-02 21:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20200902_1353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ('owner', 'page', 'image')},
        ),
    ]
