# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-12-31 18:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residents', '0005_auto_20210107_1506'),
        ('django_mailbox', '0009_alter_message_eml'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_anonymous_posts', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
                ('can_post', models.ManyToManyField(blank=True, related_name='can_post', to='residents.Person')),
                ('email_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.EmailType')),
                ('mailbox', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='django_mailbox.Mailbox')),
                ('members', models.ManyToManyField(related_name='members', to='residents.Person')),
            ],
        ),
        migrations.CreateModel(
            name='RejectedMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='django_mailbox.Message')),
            ],
        ),
    ]
