# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-03-09 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_lists', '0002_remove_mailinglist_email_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglist',
            name='can_post',
            field=models.ManyToManyField(blank=True, related_name='can_post', to='residents.Email'),
        ),
        migrations.AlterField(
            model_name='mailinglist',
            name='members',
            field=models.ManyToManyField(related_name='members', to='residents.Email'),
        ),
    ]
