# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-03-16 18:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_lists', '0008_website_update_setup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailinglist',
            options={'ordering': ('mailbox__name',)},
        ),
    ]
