# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-03-17 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_lists', '0009_auto_20250316_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglist',
            name='name_slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
