# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-03-17 13:15
from __future__ import unicode_literals

from django.db import migrations
from django.utils.text import slugify


# noinspection PyUnusedLocal
def backwards_func(apps, schema_editor):
    apps.get_model('mailing_lists', 'MailingList').objects.all().update(name_slug='')


# noinspection PyUnusedLocal
def forwards_func(apps, schema_editor):
    mailing_list_model = apps.get_model('mailing_lists', 'MailingList')

    for mailing_list in mailing_list_model.objects.all():
        mailing_list.name_slug = slugify(mailing_list.mailbox.name)
        mailing_list.save()


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_lists', '0010_mailinglist_name_slug'),
    ]

    operations = [
        migrations.RunPython(forwards_func, backwards_func)
    ]
