# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-04-27 15:27
from __future__ import unicode_literals

from django.db import migrations


# noinspection PyUnusedLocal
def backwards_func(apps, schema_editor):
    django_mailbox_model = apps.get_model('django_mailbox', 'Mailbox')
    mailing_list_model = apps.get_model('mailing_lists', 'MailingList')

    for mailbox in django_mailbox_model.objects.all():
        mailbox.uri = mailbox.uri.replace('.org', '.website')
        mailbox.save()

    for ml in mailing_list_model.objects.all():
        ml.email = ml.email.replace('.org', '.website')
        ml.save()


# noinspection PyUnusedLocal
def forwards_func(apps, schema_editor):
    django_mailbox_model = apps.get_model('django_mailbox', 'Mailbox')
    mailing_list_model = apps.get_model('mailing_lists', 'MailingList')

    for mailbox in django_mailbox_model.objects.all():
        mailbox.uri = mailbox.uri.replace('.website', '.org')
        mailbox.save()

    for ml in mailing_list_model.objects.all():
        ml.email = ml.email.replace('.website', '.org')
        ml.save()


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_lists', '0012_board_setup'),
    ]

    operations = [
        migrations.RunPython(forwards_func, backwards_func)
    ]
